version: "3"
services:
  ## Education (建议详细阅读1、2、3、4)
  douyin:
    build:
      context: ./
    environment:
      ## 1、项目环境 - 开发环境时为dev\production
      HOST: "0.0.0.0"
      CHOKIDAR_USEPOLLING: true
    container_name: douyin
    ## 2、端口映射 - 开发环境时去掉注释，并修改宿主机相应的端口
    ports:
      - "3001:3000"
    command:
      - /bin/sh
      - -c
      - |
        node
    ##yarn install
    ##yarn dev
    ##yarn start
    ##yarn start
    ##yarn dev
    ##yarn install
    ##yarn start
    ##yarn build
    ##yarn dev
    volumes:
      ## 3、项目挂载 - 开发环境时去掉注释
      - ./:/www/:rw
      ## 4、日志挂载 - 开发环境时删除或注释掉
      #- /var/log/docker/education:/var/www-log/:rw
    external_links:
      ## 5、外部容器关联 - 针对外部容器配置自己的容器名称
      - nginx
    cap_add:
      - SYS_PTRACE
    stdin_open: true
    tty: true
    networks:
      - default
networks:
  default:
    external:
      ## 6、指定network网络 - 共用外部容器网络
      name: web_default
